### ISSUE TITLE
Found usage of MDetect library without proper attribution

### ISSUE THREAD

**Issue by dev-myatminsoe** [agpyaephyo/PADC-MMNews-Kotlin#1]
I found that this app use 'org.mmtextview:mmtextview' which uses my library which is under MIT license. I don't see any license and copyright notice in this repo. Please fix. Thanks.

Original library - https://github.com/myatmins/MDetect
Usage - https://github.com/agpyaephyo/PADC-MMNews-Kotlin/blob/master/app/build.gradle

**Comment by agpyaephyo** [comment]
Lol. Sure. Can you specifically explain which part of your library is being used in  'org.mmtextview:mmtextview' library ? 

And if you want so much of attributions in this sample project that no one give a rat-ass about, you could just ask. Lol.

**Comment by dev-myatminsoe** [comment]
LOL many burmese apps which professionally support both encodings use the library. You are using it to create another library to promote your training center no one give a rat-ass about. You use stolen codes and don't even dare to upload the source codes but maven url for your students.

https://github.com/agpyaephyo/agpyaephyo.github.io/blob/master/mmtextview/index.md 

Here's a screenshot of your own comment LOL.

<img width="860" alt="screen shot 2018-07-08 at 7 45 51 pm" src="https://user-images.githubusercontent.com/6258919/42420181-b8341fcc-82e7-11e8-98c3-2f08382932ad.png">

**Comment by agpyaephyo** [comment]
LOL. "Stolen code with comment". How ironic. And think i don't teach my students how to open the source of the methods from library (any library) with control click.  And also say "I promote my class with the library". Very good drama story. You should make a movie. LOL.

**Comment by agpyaephyo** [comment]
https://github.com/agpyaephyo/agpyaephyo.github.io/issues/1
